FROM docker.io/rust:1.82.0-bullseye

RUN apt update \
 && DEBIAN_FRONTEND=noninteractive apt install -y \
        libgtk-3-dev libglib2.0-dev \
        mingw-w64 \
        gcc-aarch64-linux-gnu \
        gcc-x86-64-linux-gnux32 \
        zip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN rustup target add \
      aarch64-unknown-linux-gnu \
      x86_64-unknown-linux-gnu \
      x86_64-pc-windows-gnu

# /build.sh will be mounted by ../build.sh
# /build.sh = ./build.sh
ENTRYPOINT [ "/build.sh" ]